services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo123
    ports:
      - "5432:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: todo
      DB_PASSWORD: todo123
      DB_NAME: todoapp
    ports:
      - "222:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "1111:80"
    depends_on:
      - backend

volumes:
  todo_postgres_data:
